AWSTemplateFormatVersion: '2010-09-09'
Description: Deacon Care System Lambda, API Gateway, and IAM Role

Parameters:
  S3BucketName:
    Type: String
    Default: deacon-care-system
    Description: S3 bucket for Lambda access
  # CognitoUserPoolId:
  #   Type: String
  #   Description: The ID of the Cognito User Pool
  # CognitoAppClientId:
  #   Type: String
  #   Description: The ID of the Cognito App Client
  S3ObjectVersion:
    Type: String
    Description: The version ID of the S3 object for the Lambda function
  PlanningCenterClientId:
    Type: String
    Description: Planning Center OAuth client id
  PlanningCenterClientSecret:
    Type: String
    NoEcho: true
    Description: Planning Center OAuth client secret (NoEcho hides the value in CloudFormation outputs)
  OIDCDiscoveryUrl:
    Type: String
    Description: OIDC discovery URL for the identity provider (e.g. Planning Center)
    Default: ""
  PlanningCenterApiUrl:
    Type: String
    Description: Base API URL for Planning Center
    Default: ""
  AllowedOrganizationId:
    Type: String
    Description: The allowed organization id for the application
    Default: ""
  CustomDomainName:
    Type: String
    Description: Optional custom domain name to create for API Gateway (e.g. dcs.example.com)
    Default: ""
  CustomDomainCertificateArn:
    Type: String
    Description: ACM Certificate ARN for the custom domain (regional certificate)
    Default: ""
  # CognitoLoginUrl:
  #   Type: String
  #   Description: The login URL for the Cognito User Pool
  # CognitoUserPoolDomain:
  #   Type: String
  #   Description: The domain of the Cognito User Pool

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: actsix-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DeaconCareSystemS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !Sub arn:aws:s3:::${S3BucketName}
                  - !Sub arn:aws:s3:::${S3BucketName}/*
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  ActsixLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: actsix-site-lambda
      Handler: src/lambda.handler
      Role: !GetAtt LambdaRole.Arn
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: site-lambda.zip
        S3ObjectVersion: !Ref S3ObjectVersion
      Runtime: nodejs22.x
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          S3_BUCKET: !Ref S3BucketName
          # COGNITO_CLIENT_ID: !Ref CognitoAppClientId
          # COGNITO_LOGIN_URL: !Ref CognitoLoginUrl
          API_GATEWAY_URL: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com
          # COGNITO_USER_POOL_DOMAIN: !Ref CognitoUserPoolDomain
          PLANNING_CENTER_CLIENT_ID: !Ref PlanningCenterClientId
          PLANNING_CENTER_CLIENT_SECRET: !Ref PlanningCenterClientSecret
          OIDC_DISCOVERY_URL: !Ref OIDCDiscoveryUrl
          PLANNING_CENTER_API_URL: !Ref PlanningCenterApiUrl
          ALLOWED_ORGANIZATION_ID: !Ref AllowedOrganizationId

  ApiGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: actsix-site-lambda-http-api
      ProtocolType: HTTP

  ApiGatewayIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ApiGateway
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ActsixLambda.Arn}/invocations
      PayloadFormatVersion: '2.0'

  ApiGatewayRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGateway
      RouteKey: ANY /{proxy+}
      Target: !Sub integrations/${ApiGatewayIntegration}

  ApiGatewayStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref ApiGateway
      StageName: $default

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ActsixLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway.ApiId}/*

Conditions:
  CreateCustomDomain: !And
    - !Not [ !Equals [ !Ref CustomDomainName, "" ] ]
    - !Not [ !Equals [ !Ref CustomDomainCertificateArn, "" ] ]


  # CognitoUserPoolGroupDeacon:
  #   Type: AWS::Cognito::UserPoolGroup
  #   Properties:
  #     GroupName: deacon
  #     UserPoolId: !Ref CognitoUserPoolId

  # CognitoUserPoolGroupStaff:
  #   Type: AWS::Cognito::UserPoolGroup
  #   Properties:
  #     GroupName: staff
  #     UserPoolId: !Ref CognitoUserPoolId

  # CognitoPreSignUpTrigger:
  #   Type: AWS::Lambda::Function
  #   Properties:
  #     FunctionName: actsix-pre-signup-trigger
  #     Handler: src/userInitialization.handler
  #     Role: !GetAtt LambdaRole.Arn
  #     Code:
  #       S3Bucket: !Ref S3BucketName
  #       S3Key: site-lambda.zip
  #     Runtime: nodejs22.x
  #     Timeout: 30

  # CognitoPostConfirmationTrigger:
  #   Type: AWS::Lambda::Function
  #   Properties:
  #     FunctionName: actsix-post-confirmation-trigger
  #     Handler: src/userInitialization.handler
  #     Role: !GetAtt LambdaRole.Arn
  #     Code:
  #       S3Bucket: !Ref S3BucketName
  #       S3Key: site-lambda.zip
  #     Runtime: nodejs22.x
  #     Timeout: 30

  # CognitoUserInitializationLambda:
  #   Type: AWS::Lambda::Function
  #   Properties:
  #     FunctionName: actsix-user-initialization
  #     Handler: src/userInitialization.handler
  #     Role: !GetAtt LambdaRole.Arn
  #     Code:
  #       S3Bucket: !Ref S3BucketName
  #       S3Key: site-lambda.zip
  #     Runtime: nodejs22.x
  #     Timeout: 30
  #     Environment:
  #       Variables:
  #         S3_BUCKET: !Ref S3BucketName

  # LambdaInvokePermissionForCognito:
  #   Type: AWS::Lambda::Permission
  #   Properties:
  #     FunctionName: !Ref CognitoUserInitializationLambda
  #     Action: lambda:InvokeFunction
  #     Principal: cognito-idp.amazonaws.com
  #     SourceArn: !Sub arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUserPoolId}

  # CognitoSMSRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     RoleName: Cognito-SMS-Role
  #     AssumeRolePolicyDocument:
  #       Version: '2012-10-17'
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service: cognito-idp.amazonaws.com
  #           Action: sts:AssumeRole
  #     Policies:
  #       - PolicyName: AllowSNSPublish
  #         PolicyDocument:
  #           Version: '2012-10-17'
  #           Statement:
  #             - Effect: Allow
  #               Action:
  #                 - sns:Publish
  #               Resource: '*'

  # API Gateway custom domain (created only when both CustomDomainName and CustomDomainCertificateArn are provided)
  ApiGatewayCustomDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Condition: CreateCustomDomain
    Properties:
      DomainName: !Ref CustomDomainName
      DomainNameConfigurations:
        - CertificateArn: !Ref CustomDomainCertificateArn
          EndpointType: REGIONAL

  ApiGatewayCustomDomainMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Condition: CreateCustomDomain
    Properties:
      ApiId: !Ref ApiGateway
      DomainName: !Ref CustomDomainName
      Stage: $default

Outputs:
  LambdaName:
    Description: Lambda function name
    Value: !Ref ActsixLambda
  LambdaRoleArn:
    Description: Lambda IAM Role ARN
    Value: !GetAtt LambdaRole.Arn
  # CognitoClientId:
  #   Description: Cognito App Client ID
  #   Value: !Ref CognitoAppClientId
  ApiGatewayUrl:
    Description: API Gateway URL
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com
  CustomDomainName:
    Condition: CreateCustomDomain
    Description: Custom domain name for API Gateway (if created)
    Value: !Ref CustomDomainName
  CustomDomainArn:
    Condition: CreateCustomDomain
    Description: Domain ARN for the custom domain
    Value: !GetAtt ApiGatewayCustomDomain.DomainNameConfigurations
  # CognitoLoginUrl:
  #   Description: Cognito Login URL
  #   Value: !Ref CognitoLoginUrl
